spring:

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876

      bindings:
        addBonusConsumer-in-0:
          #消息主题（kafka）或者交换器（rabbit）
          destination: add-bonus-tx
          #content-type: text/plain #设置消息类型，默认为"application/json"
          group: add-bonus-consumer-group



    function:
      #代码中定义的函数名称
      #      definition: ss007AutoProducer;ss007Consumer
      definition: addBonusConsumer

  #      routing-expression: (headers['type']==1) ? 'ss007Consumer':'ss007Consumer2'








  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-center?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: Wjy018080
    type:  com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 10
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      keepalive-time: 30000
  redis:
    host: 121.40.131.38
    port: 6379
    database: 0
    ssl: false
    timeout: 10s
  application:
    name: user-center



